keyterms = [
    "tooth",
    "teeth",
    "Invisalign",
    "aligners",
    "prophylaxis",
    "halitosis",
    "hygienist",
    "CEREC",
    "endodontics",
    "endodontist",
    "amalgam",
    "Zoom Whitening",
    "Opalescence Whitening",
    "Lumineers",
    "gingivitis",
    "periodontist",
    "avulsed",
    "bruxism",
    "occlusal",
    "CBCT scan",
    "zirconia",
    "biocompatible",
    "occlusion",
    "intraoral",
    "pediatric",
    "periodontal",
    "Opalescence",
    "composite resin",
    "CT scan",
    "aesthetic",
    "ortho",
    "orthodontics",
    "implant-supported dentures",
    "oral appliance therapy",
    "CEREC Crowns",
    "dental sealants",
    "fluoride",
    "abscess",
    "tartar",
    "plaque",
    "dentin",
    "saliva",
    "gum contouring",
    "phobia",
    "enamel",
    "gums",
    "hygiene",
    "screening",
    "bad breath",
    "decay",
    "cavities",
    "fillings",
    "caps",
    "root canal",
    "surgical",
    "wisdom teeth removal",
    "grafting",
    "porcelain",
    "braces",
    "sedation",
    "mouthguard",
    "gum recession",
    "toothache",
    "nhs",
    "private",
    "bomi Yi",
    "dong hyun Kim",
    "ami mehta",
    "biren patel",
    "kunal patel",
    "jaesik",
    "wendy piercy",
    "rupa balaji",
    "jenna ezra",
    "hayley coughlan",
    "anita kumari bashal",
    "jae won han",
    "tabitha jayabalan",
]

MIN_ENDPOINTING_DELAY = 0.5
MAX_ENDPOINTING_DELAY = 2.5
MIN_INTERRUPTION_DURATION = 1.0
MIN_INTERRUPTION_WORDS = 2
